// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import ReactErrorBoundary from "react-error-boundary";
import * as ErrorBoundary$RescriptReactErrorBoundary from "../src/ErrorBoundary.bs.js";

function App(Props) {
  var arg = (function (error, param) {
      var message = error.message;
      console.error(message !== undefined ? message : "Unknown error occured while rendering");
    });
  return React.createElement("div", undefined, React.createElement(ReactErrorBoundary, (function (param) {
                    return ErrorBoundary$RescriptReactErrorBoundary.makeProps("Succeed!", param, undefined, arg, undefined, undefined, undefined);
                  })));
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
