// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactErrorBoundary from "react-error-boundary";
import * as ErrorBoundary$BsReactErrorBoundary from "../src/ErrorBoundary.bs.js";

function App(Props) {
  return React.createElement("div", undefined, React.createElement(ReactErrorBoundary.default, ErrorBoundary$BsReactErrorBoundary.makeProps("Succeed!", undefined, (function (error, param) {
                        var match = error.message;
                        console.error(match !== undefined ? match : "Unknown error occured while rendering");
                        return /* () */0;
                      }), /* () */0)));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
