// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function makeProps(componentStack, error, param) {
  return {
          componentStack: componentStack,
          error: error
        };
}

export {
  makeProps ,
  
}
/* No side effect */
