// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function makeProps(children, fallbackComponent, onError, param) {
  var tmp = { };
  if (children !== undefined) {
    tmp.children = Caml_option.valFromOption(children);
  }
  if (fallbackComponent !== undefined) {
    tmp.fallbackComponent = Caml_option.valFromOption(fallbackComponent);
  }
  if (onError !== undefined) {
    tmp.onError = Caml_option.valFromOption(onError);
  }
  return tmp;
}

export {
  makeProps ,
  
}
/* No side effect */
